doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                charset: utf8mb4
            server:
                # configure these for your database server
                url: '%env(resolve:DATABASE_SERVER_URL)%'
                driver: 'pdo_mysql'
                charset: utf8mb4

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            server:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: server
                mappings:
                    Server:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Server'
                        prefix: 'App\Entity\Server'
                        alias: Server
